
# This workflow integrates Qwiet preZero with GitHub
# Visit https://docs.shiftleft.io for help
name: Qwiet

on:
  pull_request:
  workflow_dispatch:
  push:

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }}   

jobs:
  Qwiet-Static-Analysis:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write
      
    steps:
    - uses: actions/checkout@v4

    # - name: Run Qwiet AI Scan
    #   uses: sandy-qwietai/qwietai-actions@main
    #   with:
    #     app_name: "your-app-name"
    #     language: java
    #   env:
    #     SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}    

    - name: Download ShiftLeft CLI
      run: |
        curl https://cdn.shiftleft.io/download/sl > ./sl && chmod a+rx ./sl 

    - name: Run sl analyze 1
      shell: bash
      run: |
        ./sl analyze --wait --verbose --app "${GITHUB_REPOSITORY_OWNER}_${GITHUB_REPOSITORY#*/}" -b ${BRANCH_NAME} .
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}

    - name: Export Sarif Report qwiet ai
      shell: bash
      run: |
        git clone https://github.com/ShiftLeftSecurity/field-integrations report
        #git clone --branch elango/exportOptions4SAST_SCA_Secret_Container --single-branch https://github.com/ShiftLeftSecurity/field-integrations report
        pip3 install -r report/shiftleft-utils/requirements.txt
        mkdir reps
        python3 report/shiftleft-utils/export.py --app elangosenthilnathan_vulnado  -f sarif --reports_dir reps --report_file qwiet-sarif-report.sarif 
        chmod -R 777 report
        gzip -c report/qwiet-sarif-report-elangosenthilnathan_vulnado.sarif | base64 -w0
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}        

    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: report/qwiet-sarif-report-elangosenthilnathan_vulnado.sarif      
        category: qwiet-prezero        

   
 

  
